#!/bin/bash

ip link set down dev eth0
ip addr flush dev eth0
ip addr add 192.168.8.5/24 dev eth0
ip link set up dev eth0

/usr/bin/docker run \
	--rm \
	--device=/dev/serial/by-id/usb-OpenMV_OpenMV_Virtual_Comm_Port_in_FS_Mode_387C357D3330-if00 \
	--device=/dev/serial/by-id/usb-OpenMV_OpenMV_Virtual_Comm_Port_in_FS_Mode_3172326E3330-if00 \
	--network host \
	--cap-add SYS_TIME \
	ros2	
