#!/bin/bash

ip link set down dev eth0
ip addr flush dev eth0
ip addr add 192.168.8.5/24 dev eth0
ip link set up dev eth0

/usr/bin/docker run \
	--rm \
	-/dev:/dev \
	--network host \
	--cap-add SYS_TIME \
	ros2	
